### ISSUE TITLE
Web Demo Link Broken?

### ISSUE THREAD

**Issue by hydrosquall** [Caleydo/domino_js#5]
Hi,

Is there a standalone web demo currently functioning? I get a DNS server error when I click the link on the "web prototype" button on the [project page](http://caleydo.org/tools/domino/)

http://playground.caleydo.org/domino_js/

**Comment by mstreit** [comment]
Hi,

Thanks for your interest in our work! Unfortunately, we don't have a working domino implementation at the moment. I've removed the link on the website. Sorry for the confusion.

Cheers,
Marc
